spring:

  datasource:
    #url: jdbc:mysql://localhost:3306/hotel?useSSL=false&serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/hotel
    username: root
    password:

  jpa:
    show-sql: true