spring:

  datasource:
    url: jdbc:mysql://localhost:3306/hotel?useSSL=false&serverTimezone=UTC
    username: root
    password:

  jpa:
    show-sql: true

  jwt-security:
    secret: testkey1234
    expiration-time: 360